version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://localhost:27017/Ecommerce-Products
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
